### ISSUE TITLE
Failed to activate the artisan package

### ISSUE THREAD

**Issue by W2YN** [dzava/atom-artisan#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [artisan](https://github.com/dzava/atom-artisan) package 0.3.1

### Stack Trace

Failed to activate the artisan package

```
At customCommands.concat is not a function

TypeError: customCommands.concat is not a function
    at Object.loadCommands (/packages/artisan/lib/artisan.js:92:40)
    at Object.registerCommands (/packages/artisan/lib/artisan.js:70:27)
    at Object.activate (/packages/artisan/lib/artisan.js:58:10)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.2/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.23.2/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.23.2/resources/app/src/package-manager.js:647:50)
    at ~/AppData/Local/atom/app-1.23.2/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
artisan 0.3.1 
larasnippets 0.44.0 
php-fmt 0.1.2 
```

**Comment by dzava** [comment]
Make sure the file that the `Custom commands` setting points to is a valid json file containing an array of commands.

e.g.
```json
[
    {
        "caption": "Enter the name of the command you need help with",
        "command": "help",
        "name": "help",
        "needsInput": true,
        "showInPanel": true
    },
    {
        "command": "clear-compiled",
        "name": "clear compiled"
    }
]
```
